{{- if .Values.initScript.createUser.userEnabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: consumer-user-create-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  containers:
    - name: consumer-keyrock-user-create
      image: quay.io/wi_stefan/python:3
      command:
        - /bin/sh
        - /scripts/entrypoint.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
  volumes:
    - name: scripts
      configMap:
        name: consumer-{{ .Values.initScript.createUser.id }}-user-cm
  restartPolicy: Never

{{- end }}
