postgresql:
  fullnameOverride: postgresql
  auth:
    username: keycloak
    enablePostgresUser: true
    postgresPassword: dbRootPassword
    password: dbPassword
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use    
  primary:
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE i4t_consumer_kc;"
