apiVersion: v2
name: i4trust-consumer
description: Helm chart to deploy the i4Trust service consumer components
type: application
version: 0.0.1
maintainers:
  - name: Dennis Wendland
    email: dennis.wendland@fiware.org
