## values to be used for deployement in PoC namespaces
## additional config file is used, since we rely on managed databases there.

source: https://github.com/FIWARE-Ops/i4trust-consumer
release: i4t-consumer-demo
destination_namespace: &destination i4t-consumer-demo
purpose: &purpose i4trust-demonstrator-env
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: postgresql
    enabled: true
    source_path: applications/postgresql
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: consumer-waltid
    enabled: true
    source_path: applications/consumer-waltid
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: consumer-keycloak
    enabled: true
    source_path: applications/consumer-keycloak
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values:
      realm:
        id: hp
        displayName: "Keycloak Consumer"
        displayNameHtml: "<div class=\"kc-logo-text\"><span>Keycloak</span></div>"
        user:
          - username: max.prime
            email: max.prime@mymail.com
            password: prime
            - username: steve.standard
              email: steve.standard@mymail.com
              password: standard
        frontend:
          url: https://consumer-keycloak-i4t-consumer-main.apps.fiware.fiware.dev
      keycloak:
        keycloakConfigCli:
          existingConfigmap: consumer-keycloak-hp-realm
        extraVolumes:
          - name: profiles
            configMap:
              name: consumer-keycloak-hp-profile
          - name: providers
            emptyDir: {}

  - name: consumer-keyrock
    enabled: true
    source_path: applications/consumer-keyrock
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        host: https://consumer-keyrock-0-i4t-consumer-main.apps.fiware.fiware.dev
        satellite:
          # Need to specify valid satellite hostname here
          url: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev"
          tokenEndpoint: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev/token"
          partiesEndpoint: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev/parties"

  - name: consumer-keyrock-shop
    enabled: true
    source_path: applications/consumer-keyrock-shop
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        host: https://consumer-keyrock-shop-0-i4t-consumer-main.apps.fiware.fiware.dev
        satellite:
          # Need to specify valid satellite hostname here
          url: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev"
          tokenEndpoint: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev/token"
          partiesEndpoint: "https://ishare-satellite-i4t-consumer-main.apps.fiware.fiware.dev/parties"

  
