route:
  enabled: true
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

realm:
  id: hp
  displayName: "Keycloak Consumer"
  displayNameHtml: "<div class=\"kc-logo-text\"><span>Keycloak</span></div>"
  did: "did:key:abc"
  user:
    - username: max.prime
      email: max.prime@mymail.com
      password: prime
    - username: steve.standard
      email: steve.standard@mymail.com
      password: standard
  frontend:
    url: https://consumer-keycloak-i4t-consumer-main.apps.fiware.fiware.dev
  orionPep:
    baseUrl: https://orion-ld
    adminUrl: https://orion-ld
    redirectUris:
      - https://orion-ld/
    webOrigins:
      - https://orion-ld/

keycloak:
  logging:
    level: INFO
  replicaCount: 1
  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  
  keycloakConfigCli:
    enabled: true
    # current image does not contain 20.0.3., thus we need this fix
    command: 
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.1.jar

    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    existingConfigmap: consumer-keycloak-hp-realm
  
  extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_LOG_LEVEL
    value: INFO
  #- name: VCISSUER_ISSUER_DID
  #  value: "did:key:abc"
  - name: VCISSUER_WALTID_ADDRESS
    value: "http://consumer-waltid"
  #- name: VCISSUER_ISSUER_KEY_FILE
  #  value: /opt/keys/keyfile.json


  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
    - name: providers
      mountPath: /opt/bitnami/keycloak/providers/
    #- name: issuer-key
    #  mountPath: /opt/keys

  extraVolumes:
    - name: profiles
      configMap:
        name: consumer-keycloak-hp-profile
    - name: providers
      emptyDir: {}
    #- name: issuer-key
    #  configMap:
    #    name: keycloak-one-key


  initContainers:
    - name: add-vc-issuer
      image: quay.io/fiware/keycloak-vc-issuer:0.3.1
      imagePullPolicy: Always
      volumeMounts:
        - name: providers
          mountPath: /target
  
  postgresql:
    enabled: false

  externalDatabase:
    host: postgresql
    user: keycloak
    database: i4t_consumer_kc
    password: dbPassword
